# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
orbs: 
  gcp-cli: circleci/gcp-cli@2.4.0
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    machine:
      image: ubuntu-2004:202111-02
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      # https://circleci.com/docs/2.0/google-auth/
      - run:
          name: Google auth
          command: |
            echo $GCLOUD_SERVICE_KEY > key.json
            cat key.json | docker login -u _json_key_base64 --password-stdin \
            https://us-east1-docker.pkg.dev
      - run:
          name: "Run docker container ✔️"
          command: |
            result=$(docker run --rm -p 8080:8080 us-east1-docker.pkg.dev/marketplaceinspace/test/phoenix-journey/hi_nutek:f23c81f2923294e7289e9c517544137dc01155d8)
            mkdir tmp
            echo $result >> tmp/nutek
      # save latest version to github     
      - run: 
          name: Git user name and email
          command: |-
            git config --global user.name "Szymon" && \
            git config --global user.email "github-bot@phoenixjourney.com"      
      - run: 
          name: Git add
          command: |-
            git add -A
      - run: 
          name: Git commit
          command: |-
            git commit -m "Commit app intent/outcome from Phoenix Journey [skip ci]"
      - run: 
          name: Git pull
          command: |-
            git pull --rebase origin $CIRCLE_BRANCH
      - run: 
          name: Git push
          command: |-
            git push origin $CIRCLE_BRANCH
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello:
          context:
              - test
